---
name: Build

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t apache-hostname .

      - name: Run the built image.
        run: >-
          docker run --name test-instanciation -d apache-hostname

      # TODO : test apache is running or curl message

  # If on main branch, build and release image.
  release_latest:
    name: Release latest
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: francois/test_ghactions:latest

  release_tags:
    name: Release tag
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          #tags: francois/test_ghactions:${{  github.ref_name }}"
          #tags: francois/test_ghactions:${GITHUB_REF##*/}
          tags: francois/test_ghactions:${{ env.GIT_REF }}
